export const GENRES = [
    "Psychology",
    "Science Fiction",
    "Self-Help",
    "Medicine",
    "Arts",
    "History",
    "Economics",
    "Finance",
    "Politics",
    "Law",
    "Thriller",
    "Science",
    "Neuroscience",
    "Fiction",
    "Non-Fiction",
    "Fantasy",
    "Mystery",
    "Romance",
    "Horror",
    "Biography",
    "Autobiography",
    "Poetry",
    "Drama",
    "Philosophy",
    "Religion",
    "Spirituality",
    "Business",
    "Technology",
    "Computer Science",
    "Mathematics",
    "Physics",
    "Biology",
    "Sociology",
    "Education",
    "Travel",
    "Cooking",
    "Sports",
    "Health & Fitness",
    "Parenting",
    "Children's",
    "Young Adult",
    "Classics",
    "Adventure",
    "Crime",
    "True Crime",
    "Humor",
    "Music",
];